# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ProtoCommit(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'author': 'ProtoCommitAuthor',
        'date': 'datetime',
        'message': 'str',
        'sha': 'str'
    }

    attribute_map = {
        'author': 'author',
        'date': 'date',
        'message': 'message',
        'sha': 'sha'
    }

    def __init__(self, author=None, date=None, message=None, sha=None, local_vars_configuration=None):  # noqa: E501
        """ProtoCommit - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._author = None
        self._date = None
        self._message = None
        self._sha = None
        self.discriminator = None

        self.author = author
        self.date = date
        self.message = message
        self.sha = sha

    @property
    def author(self):
        """Gets the author of this ProtoCommit.  # noqa: E501


        :return: The author of this ProtoCommit.  # noqa: E501
        :rtype: ProtoCommitAuthor
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this ProtoCommit.


        :param author: The author of this ProtoCommit.  # noqa: E501
        :type author: ProtoCommitAuthor
        """
        if self.local_vars_configuration.client_side_validation and author is None:  # noqa: E501
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def date(self):
        """Gets the date of this ProtoCommit.  # noqa: E501


        :return: The date of this ProtoCommit.  # noqa: E501
        :rtype: datetime
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this ProtoCommit.


        :param date: The date of this ProtoCommit.  # noqa: E501
        :type date: datetime
        """
        if self.local_vars_configuration.client_side_validation and date is None:  # noqa: E501
            raise ValueError("Invalid value for `date`, must not be `None`")  # noqa: E501

        self._date = date

    @property
    def message(self):
        """Gets the message of this ProtoCommit.  # noqa: E501


        :return: The message of this ProtoCommit.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ProtoCommit.


        :param message: The message of this ProtoCommit.  # noqa: E501
        :type message: str
        """
        if self.local_vars_configuration.client_side_validation and message is None:  # noqa: E501
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def sha(self):
        """Gets the sha of this ProtoCommit.  # noqa: E501


        :return: The sha of this ProtoCommit.  # noqa: E501
        :rtype: str
        """
        return self._sha

    @sha.setter
    def sha(self, sha):
        """Sets the sha of this ProtoCommit.


        :param sha: The sha of this ProtoCommit.  # noqa: E501
        :type sha: str
        """
        if self.local_vars_configuration.client_side_validation and sha is None:  # noqa: E501
            raise ValueError("Invalid value for `sha`, must not be `None`")  # noqa: E501

        self._sha = sha

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProtoCommit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProtoCommit):
            return True

        return self.to_dict() != other.to_dict()
