TRANSACTIONS_USER_COL = 0
TRANSACTIONS_ITEM_COL = 1
TRANSACTIONS_RATING_COL = 2

FEATURES_ID_COL = 0

TRANSACTION_DATASET = "Transaction dataset"
ITEM_FEATURE_DATASET = "Item feature dataset"
USER_FEATURE_DATASET = "User feature dataset"

RANDOM_SEED = 42

MODEL_SAVE_FILE = "_model.pkl"

TUPLE_SEP = ","
