# coding: utf-8

"""
    AristaFlowREST/ResModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_res_model_manager
from af_res_model_manager.models.process_start_ref_attribute import ProcessStartRefAttribute  # noqa: E501
from af_res_model_manager.rest import ApiException


class TestProcessStartRefAttribute(unittest.TestCase):
    """ProcessStartRefAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessStartRefAttribute(self):
        """Test ProcessStartRefAttribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_res_model_manager.models.process_start_ref_attribute.ProcessStartRefAttribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
