class BillingAddress:
    def __init__(self, street='',
                        region='',
                        reference='',
                        detail='',
                        postcode='',
                        phone='',
                        number='',
                        neighborhood='',
                        full_name='',
                        country='',
                        city=''):
        self.street = street
        self. region = region
        self.reference = reference
        self.detail = detail
        self.postcode = postcode
        self.phone = phone
        self.number = number
        self.neighborhood = neighborhood
        self.full_name = full_name
        self.country = country
        self.city = city

class Payment:
    def __init__(self, value='',
                        transaction_date='',
                        status='',
                        type_integration='',
                        payment_indicator='',
                        name_payment='',
                        name_card_issuer='',
                        id_payment='',
                        id_card_issuer='',
                        parcels='',
                        method='',
                        description='',
                        card_issuer='',
                        autorization_id=''):
        self.value = value
        self.transaction_date = transaction_date
        self.status = status
        self.type_integration = type_integration
        self.payment_indicator = payment_indicator
        self.name_payment = name_payment
        self.name_card_issuer = name_card_issuer
        self.id_payment = id_payment
        self.id_card_issuer = id_card_issuer
        self.parcels = parcels
        self.method = method
        self.description = description
        self.card_issuer = card_issuer
        self.autorization_id = autorization_id

class Customer:
    def __init__(self, vat_number='',
                        phones=[],
                        name='',
                        gender='',
                        email='',
                        date_of_birth=''):
        self.vat_number = vat_number
        self.phones = phones
        self.name = name
        self.gender = gender
        self.email = email
        self.date_of_birth = date_of_birth

class Status:
    def __init__(self, _type='',
                        label='',
                        code=''):
        self._type = _type
        self.label = label
        self.code = code

class ShippingAddress:
    def __init__(self, street='',
                        region='',
                        reference='',
                        detail='',
                        postcode='',
                        phone='',
                        number='',
                        neighborhood='',
                        full_name='',
                        country='',
                        city=''):
        self.street = street
        self.region = region
        self.reference = reference
        self.detail = detail
        self.postcode = postcode
        self.phone = phone
        self.number = number
        self.neighborhood = neighborhood
        self.full_name = full_name
        self.country = country
        self.city = city

class Item:
    def __init__(self, special_price='',
                        shipping_cost='',
                        qty='',
                        product_id='',
                        original_price='',
                        name='',
                        gift_wrap=''):
        self.special_price = special_price
        self.shipping_cost = shipping_cost
        self.qty = qty
        self.product_id = product_id
        self.original_price = original_price
        self.name = name
        self.gift_wrap = gift_wrap

class Invoice:
    def __init__(self, number='',
                        key='',
                        line='',
                        issue_date='',
                        volume_qty=''):
        self.number = number
        self.key = key
        self.line = line
        self.issue_date = issue_date
        self.volume_qty = volume_qty

class Order:
    def __init__(self, code='',
                        billing_address=dict(),
                        invoices=[],
                        payments=[],
                        seller_shipping_cost='',
                        updated_at='',
                        customer=dict(),
                        status=dict(),
                        placed_at='',
                        channel='',
                        shipments=[],
                        approved_date='',
                        shipping_address=dict(),
                        shipping_cost='',
                        estimated_delivery='',
                        discount='',
                        shipping_method='',
                        delivered_date='',
                        items=[],
                        shipping_carrier='',
                        shipped_date='',
                        total_ordered=''):
        self.code = code
        self.billing_address = billing_address
        self.invoices = invoices
        self.payments = payments
        self.seller_shipping_cost = seller_shipping_cost
        self.updated_at = updated_at
        self.customer = customer
        self.status = status
        self.placed_at = placed_at
        self.channel = channel
        self.shipments = shipments
        self.approved_date = approved_date
        self.shipping_address = shipping_address
        self.shipping_cost = shipping_cost
        self.estimated_delivery = estimated_delivery
        self.discount = discount
        self.shipping_method = shipping_method
        self.delivered_date = delivered_date
        self.items = items
        self.shipping_carrier = shipping_carrier
        self.shipped_date = shipped_date
        self.total_ordered = total_ordered