"""A dict of OFFSETS for supported networks."""
OFFSETS = {
    'lenet5': 0,
    'vgg19': 1,
    'resnet50': 1,
    'resnet50_mlperf': 0,
    'resnet50_v2': 1,
    'resnet34': 1,
    'resnet152': 1,
    'seresnet50': 1,
    'senet154': 1,
    'resnext50': 1,
    'inception_v1': 0,
    'inception_v2': 0,
    'inception_v3': 1,
    'inception_v4': 0,
    'xception': 1,
    'pnasnet_large': 0,
    'pnasnet_mobile': 0,
    'nasnet_mobile': 0,
    'mobilenet_v1': 0,
    'mobilenet_v2': 0,
    'mobilenet_v1_mlperf': 0,
    'squeezenet': 1,
    'densenet121': 1,
    'efficientnet_b0': 1,
    'efficientnet_b1': 1,
    'efficientnet_b2': 1,
    'efficientnet_b3': 1,
    'efficientnet_b4': 1,
    'efficientnet_b5': 1,
}
