APPEND_SCORE_COLUMNS_TO_OUTPUT_KEY = "Append score columns to output"
SCORED_LABEL_COL_NAME = "Scored Label"
SERIALIZATION_METHOD_KEY = "serialization_format"
MODEL_FILE_PATH_KEY = "model_file_path"
MODEL_SPEC_FILE_NAME = "model_spec.yaml"
