class Product:
    def __init__(self, sku='',
                        name='',
                        description='',
                        status='',
                        removed='',
                        qty='',
                        price='',
                        promotional_price='',
                        cost='',
                        weight='',
                        height='',
                        width='',
                        length='',
                        brand='',
                        ean='',
                        nbm='',
                        categories=[],
                        images=[],
                        specifications=[],
                        variations=[],
                        variation_attributes=[]):
        self.sku = sku
        self.name = name
        self.description = description
        self.status = status
        self.removed = removed
        self.qty = qty
        self.price = price
        self.promotional_price = promotional_price
        self.cost = cost
        self.weight = weight
        self.height = height
        self.width = width
        self.length = length
        self.brand = brand
        self.ean = ean
        self.nbm = nbm
        self.categories = categories
        self.images = images
        self.specifications = specifications
        self.variations = variations
        self.variation_attributes = variation_attributes