# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ClusterValidationId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    MACHINE_CIDR_DEFINED = "machine-cidr-defined"
    CLUSTER_CIDR_DEFINED = "cluster-cidr-defined"
    SERVICE_CIDR_DEFINED = "service-cidr-defined"
    NO_CIDRS_OVERLAPPING = "no-cidrs-overlapping"
    NETWORK_PREFIX_VALID = "network-prefix-valid"
    MACHINE_CIDR_EQUALS_TO_CALCULATED_CIDR = "machine-cidr-equals-to-calculated-cidr"
    API_VIP_DEFINED = "api-vip-defined"
    API_VIP_VALID = "api-vip-valid"
    INGRESS_VIP_DEFINED = "ingress-vip-defined"
    INGRESS_VIP_VALID = "ingress-vip-valid"
    ALL_HOSTS_ARE_READY_TO_INSTALL = "all-hosts-are-ready-to-install"
    SUFFICIENT_MASTERS_COUNT = "sufficient-masters-count"
    DNS_DOMAIN_DEFINED = "dns-domain-defined"
    PULL_SECRET_SET = "pull-secret-set"
    NTP_SERVER_CONFIGURED = "ntp-server-configured"
    LSO_REQUIREMENTS_SATISFIED = "lso-requirements-satisfied"
    OCS_REQUIREMENTS_SATISFIED = "ocs-requirements-satisfied"
    CNV_REQUIREMENTS_SATISFIED = "cnv-requirements-satisfied"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """ClusterValidationId - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterValidationId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterValidationId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
