# coding: utf-8

"""
    Agilicus API

    Agilicus API endpoints  # noqa: E501

    The version of the OpenAPI document: 2021.03.19
    Contact: dev@agilicus.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import agilicus_api
from agilicus_api.models.connector_stats_metadata import ConnectorStatsMetadata  # noqa: E501
from agilicus_api.rest import ApiException

class TestConnectorStatsMetadata(unittest.TestCase):
    """ConnectorStatsMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConnectorStatsMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = agilicus_api.models.connector_stats_metadata.ConnectorStatsMetadata()  # noqa: E501
        if include_optional :
            return ConnectorStatsMetadata(
                creation_time = '2020-07-07T15:40:46.010Z', 
                collection_time = '2020-07-07T15:49:51.230Z', 
                receipt_time = '2020-07-07T15:49:51.530Z'
            )
        else :
            return ConnectorStatsMetadata(
                collection_time = '2020-07-07T15:49:51.230Z',
        )

    def testConnectorStatsMetadata(self):
        """Test ConnectorStatsMetadata"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
