# EVE IDs
EVE_CATEGORY_ID_SHIP = 6
EVE_CATEGORY_ID_BLUEPRINT = 9
EVE_CATEGORY_ID_STRUCTURE = 65
EVE_CATEGORY_ID_SKIN = 91

EVE_GROUP_ID_PLANET = 7
EVE_GROUP_ID_MOON = 8
EVE_GROUP_ID_ASTEROID_BELT = 9
EVE_GROUP_ID_STARGATE = 10
EVE_GROUP_ID_STATION = 15
