from perceptilabs.modelrecommender.decoders.base import DecoderBlueprint
from perceptilabs.modelrecommender.decoders.numerical import NumericalDecoderBlueprint
from perceptilabs.modelrecommender.decoders.categorical import CategoricalDecoderBlueprint
