from . import crm_leads_validate
from . import crm_lead_lines_validate
from . import contract_iban_change
from . import contract_holder_change
from . import contract_email_change
from . import contract_address_change
from . import contract_one_shot_request
from . import contract_tariff_change
from . import move_line_add_to_payment_debit_order
from . import invoice_claim_1_send
from . import create_subscription_from_partner
from . import create_lead_from_partner
from . import contract_invoice_payment
from . import import_payment_group
from . import mail_compose_message
