from distutils.core import setup
setup(
  name = 'libmp',
  packages = ['libmp'],
  version = '0.1',
  license='MIT',
  description = 'LIBRARY FOR SUPPORT FUNCTIONS AND METHODS AT WORK FOR GROUP MULTIPECAS FROM BRAZIL',
  author = 'LUCAS GARCIA RIBEIRO',
  author_email = 'lucasgr7@gmail.com',
  url = 'https://onlinemotopecas.com.br/',
  download_url = 'https://github.com/lucasgr7/libmp/archive/refs/tags/v0.1.tar.gz',
  keywords = ['LIBRARY', 'MULTIPECAS', 'API', 'MERCADOLIVRE'],
  #install_requires=[],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
  ],
)