"""
    Digital Model API (WIP)

    Digital Model API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.action_delay_input import ActionDelayInput
from openapi_client.model.property_cpu_response_links import PropertyCPUResponseLinks
globals()['ActionDelayInput'] = ActionDelayInput
globals()['PropertyCPUResponseLinks'] = PropertyCPUResponseLinks
from openapi_client.model.action_delay_response import ActionDelayResponse


class TestActionDelayResponse(unittest.TestCase):
    """ActionDelayResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionDelayResponse(self):
        """Test ActionDelayResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActionDelayResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
