# AUTOGENERATED! DO NOT EDIT! File to edit: catalog.ipynb (unless otherwise specified).

__all__ = ['conf_loader', 'conf_test_data_catalog', 'test_data_catalog']

# Cell

from kedro.config import ConfigLoader
from kedro.io import DataCatalog


# Cell
conf_loader = ConfigLoader("conf/base")
conf_test_data_catalog = conf_loader.get("catalog*.yaml", "catalog*/*.yaml")
test_data_catalog = DataCatalog.from_config(conf_test_data_catalog)
