
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-21T01:05:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0b2c10a753ffb7590525761b30dbed5b51f3092",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
