import abc
import builtins
import datetime
import enum
import typing

import jsii
import publication
import typing_extensions

import aws_cdk.alexa_ask._jsii
import aws_cdk.aws_accessanalyzer._jsii
import aws_cdk.aws_acmpca._jsii
import aws_cdk.aws_amazonmq._jsii
import aws_cdk.aws_amplify._jsii
import aws_cdk.aws_apigateway._jsii
import aws_cdk.aws_apigatewayv2._jsii
import aws_cdk.aws_appconfig._jsii
import aws_cdk.aws_appflow._jsii
import aws_cdk.aws_applicationautoscaling._jsii
import aws_cdk.aws_applicationinsights._jsii
import aws_cdk.aws_appmesh._jsii
import aws_cdk.aws_appstream._jsii
import aws_cdk.aws_appsync._jsii
import aws_cdk.aws_athena._jsii
import aws_cdk.aws_auditmanager._jsii
import aws_cdk.aws_autoscaling._jsii
import aws_cdk.aws_autoscalingplans._jsii
import aws_cdk.aws_backup._jsii
import aws_cdk.aws_batch._jsii
import aws_cdk.aws_budgets._jsii
import aws_cdk.aws_cassandra._jsii
import aws_cdk.aws_ce._jsii
import aws_cdk.aws_certificatemanager._jsii
import aws_cdk.aws_chatbot._jsii
import aws_cdk.aws_cloud9._jsii
import aws_cdk.aws_cloudfront._jsii
import aws_cdk.aws_cloudtrail._jsii
import aws_cdk.aws_cloudwatch._jsii
import aws_cdk.aws_codeartifact._jsii
import aws_cdk.aws_codebuild._jsii
import aws_cdk.aws_codecommit._jsii
import aws_cdk.aws_codedeploy._jsii
import aws_cdk.aws_codeguruprofiler._jsii
import aws_cdk.aws_codegurureviewer._jsii
import aws_cdk.aws_codepipeline._jsii
import aws_cdk.aws_codestar._jsii
import aws_cdk.aws_codestarconnections._jsii
import aws_cdk.aws_codestarnotifications._jsii
import aws_cdk.aws_cognito._jsii
import aws_cdk.aws_config._jsii
import aws_cdk.aws_databrew._jsii
import aws_cdk.aws_datapipeline._jsii
import aws_cdk.aws_datasync._jsii
import aws_cdk.aws_dax._jsii
import aws_cdk.aws_detective._jsii
import aws_cdk.aws_devopsguru._jsii
import aws_cdk.aws_directoryservice._jsii
import aws_cdk.aws_dlm._jsii
import aws_cdk.aws_dms._jsii
import aws_cdk.aws_docdb._jsii
import aws_cdk.aws_dynamodb._jsii
import aws_cdk.aws_ec2._jsii
import aws_cdk.aws_ecr._jsii
import aws_cdk.aws_ecs._jsii
import aws_cdk.aws_efs._jsii
import aws_cdk.aws_eks._jsii
import aws_cdk.aws_elasticache._jsii
import aws_cdk.aws_elasticbeanstalk._jsii
import aws_cdk.aws_elasticloadbalancing._jsii
import aws_cdk.aws_elasticloadbalancingv2._jsii
import aws_cdk.aws_elasticsearch._jsii
import aws_cdk.aws_emr._jsii
import aws_cdk.aws_emrcontainers._jsii
import aws_cdk.aws_events._jsii
import aws_cdk.aws_eventschemas._jsii
import aws_cdk.aws_fis._jsii
import aws_cdk.aws_fms._jsii
import aws_cdk.aws_fsx._jsii
import aws_cdk.aws_gamelift._jsii
import aws_cdk.aws_globalaccelerator._jsii
import aws_cdk.aws_glue._jsii
import aws_cdk.aws_greengrass._jsii
import aws_cdk.aws_greengrassv2._jsii
import aws_cdk.aws_guardduty._jsii
import aws_cdk.aws_iam._jsii
import aws_cdk.aws_imagebuilder._jsii
import aws_cdk.aws_inspector._jsii
import aws_cdk.aws_iot._jsii
import aws_cdk.aws_iot1click._jsii
import aws_cdk.aws_iotanalytics._jsii
import aws_cdk.aws_iotevents._jsii
import aws_cdk.aws_iotsitewise._jsii
import aws_cdk.aws_iotthingsgraph._jsii
import aws_cdk.aws_iotwireless._jsii
import aws_cdk.aws_ivs._jsii
import aws_cdk.aws_kendra._jsii
import aws_cdk.aws_kinesis._jsii
import aws_cdk.aws_kinesisanalytics._jsii
import aws_cdk.aws_kinesisfirehose._jsii
import aws_cdk.aws_kms._jsii
import aws_cdk.aws_lakeformation._jsii
import aws_cdk.aws_lambda._jsii
import aws_cdk.aws_licensemanager._jsii
import aws_cdk.aws_logs._jsii
import aws_cdk.aws_lookoutvision._jsii
import aws_cdk.aws_macie._jsii
import aws_cdk.aws_managedblockchain._jsii
import aws_cdk.aws_mediaconnect._jsii
import aws_cdk.aws_mediaconvert._jsii
import aws_cdk.aws_medialive._jsii
import aws_cdk.aws_mediapackage._jsii
import aws_cdk.aws_mediastore._jsii
import aws_cdk.aws_msk._jsii
import aws_cdk.aws_mwaa._jsii
import aws_cdk.aws_neptune._jsii
import aws_cdk.aws_networkfirewall._jsii
import aws_cdk.aws_networkmanager._jsii
import aws_cdk.aws_opsworks._jsii
import aws_cdk.aws_opsworkscm._jsii
import aws_cdk.aws_pinpoint._jsii
import aws_cdk.aws_pinpointemail._jsii
import aws_cdk.aws_qldb._jsii
import aws_cdk.aws_quicksight._jsii
import aws_cdk.aws_ram._jsii
import aws_cdk.aws_rds._jsii
import aws_cdk.aws_redshift._jsii
import aws_cdk.aws_resourcegroups._jsii
import aws_cdk.aws_robomaker._jsii
import aws_cdk.aws_route53._jsii
import aws_cdk.aws_route53resolver._jsii
import aws_cdk.aws_s3._jsii
import aws_cdk.aws_s3objectlambda._jsii
import aws_cdk.aws_s3outposts._jsii
import aws_cdk.aws_sagemaker._jsii
import aws_cdk.aws_sam._jsii
import aws_cdk.aws_sdb._jsii
import aws_cdk.aws_secretsmanager._jsii
import aws_cdk.aws_securityhub._jsii
import aws_cdk.aws_servicecatalog._jsii
import aws_cdk.aws_servicecatalogappregistry._jsii
import aws_cdk.aws_servicediscovery._jsii
import aws_cdk.aws_ses._jsii
import aws_cdk.aws_signer._jsii
import aws_cdk.aws_sns._jsii
import aws_cdk.aws_sqs._jsii
import aws_cdk.aws_ssm._jsii
import aws_cdk.aws_sso._jsii
import aws_cdk.aws_stepfunctions._jsii
import aws_cdk.aws_synthetics._jsii
import aws_cdk.aws_timestream._jsii
import aws_cdk.aws_transfer._jsii
import aws_cdk.aws_waf._jsii
import aws_cdk.aws_wafregional._jsii
import aws_cdk.aws_wafv2._jsii
import aws_cdk.aws_workspaces._jsii
import aws_cdk.core._jsii
import constructs._jsii

__jsii_assembly__ = jsii.JSIIAssembly.load(
    "@aws-cdk/cloudformation-include",
    "1.95.0",
    __name__[0:-6],
    "cloudformation-include@1.95.0.jsii.tgz",
)

__all__ = [
    "__jsii_assembly__",
]

publication.publish()
