print("###                                     ######        ")
print(" #  #    # ##### ###### #      #      # #     # #   # ")
print(" #  ##   #   #   #      #      #      # #     #  # #  ")
print(" #  # #  #   #   #####  #      #      # ######    #   ")
print(" #  #  # #   #   #      #      #      # #         #   ")
print(" #  #   ##   #   #      #      #      # #         #   ")
print("### #    #   #   ###### ###### ###### # #         #   ")
print("\n")
print("A Python GUI for automatic Analyses of IntelliCage Data")
print("For more information see https://github.com/NiRuff/IntelliPy/")
print("Author: Nicolas Ruffini")