'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._928 import AddendumModificationDistributionRule
    from ._929 import BacklashSpecification
    from ._930 import BasicRackProfiles
    from ._931 import CaseHardeningProperties
    from ._932 import CreateNewSuitableCutterOption
    from ._933 import CrossedAxisCylindricalGearPair
    from ._934 import CrossedAxisCylindricalGearPairLineContact
    from ._935 import CrossedAxisCylindricalGearPairPointContact
    from ._936 import CylindricalGearAbstractRack
    from ._937 import CylindricalGearAbstractRackFlank
    from ._938 import CylindricalGearBasicRack
    from ._939 import CylindricalGearBasicRackFlank
    from ._940 import CylindricalGearCuttingOptions
    from ._941 import CylindricalGearDefaults
    from ._942 import CylindricalGearDesign
    from ._943 import CylindricalGearDesignConstraint
    from ._944 import CylindricalGearDesignConstraints
    from ._945 import CylindricalGearDesignConstraintsDatabase
    from ._946 import CylindricalGearDesignConstraintSettings
    from ._947 import CylindricalGearDesignSettings
    from ._948 import CylindricalGearFlankDesign
    from ._949 import CylindricalGearMeshDesign
    from ._950 import CylindricalGearMeshFlankDesign
    from ._951 import CylindricalGearPinionTypeCutter
    from ._952 import CylindricalGearPinionTypeCutterFlank
    from ._953 import CylindricalGearProfileMeasurement
    from ._954 import CylindricalGearProfileMeasurementType
    from ._955 import CylindricalGearProfileModifications
    from ._956 import CylindricalGearSetDesign
    from ._957 import CylindricalGearSetFlankDesign
    from ._958 import CylindricalGearSetMacroGeometryOptimiser
    from ._959 import CylindricalGearSetManufacturingConfigurationSelection
    from ._960 import CylindricalGearTableMGItemDetail
    from ._961 import CylindricalGearTableWithMGCharts
    from ._962 import CylindricalGearToothThicknessSpecification
    from ._963 import CylindricalMeshAngularBacklash
    from ._964 import CylindricalMeshedGear
    from ._965 import CylindricalMeshedGearFlank
    from ._966 import CylindricalMeshLinearBacklashSpecification
    from ._967 import CylindricalPlanetaryGearSetDesign
    from ._968 import CylindricalPlanetGearDesign
    from ._969 import DIN3967AllowanceSeries
    from ._970 import DIN3967ToleranceSeries
    from ._971 import FinishStockSpecification
    from ._972 import FinishToothThicknessDesignSpecification
    from ._973 import GearFitSystems
    from ._974 import GearManufacturingConfigSetupViewModel
    from ._975 import GearSetFCAImportSetup
    from ._976 import GearSetManufacturingConfigurationSetup
    from ._977 import GeometrySpecificationType
    from ._978 import HardenedMaterialProperties
    from ._979 import HardnessProfileCalculationMethod
    from ._980 import HeatTreatmentType
    from ._981 import ISO6336Geometry
    from ._982 import ISO6336GeometryBase
    from ._983 import ISO6336GeometryForShapedGears
    from ._984 import ISO6336GeometryManufactured
    from ._985 import LinearBacklashSepcification
    from ._986 import LTCALoadCaseModifiableSettings
    from ._987 import LtcaSettings
    from ._988 import MicroGeometryConvention
    from ._989 import MicroGeometryProfileConvention
    from ._990 import Micropitting
    from ._991 import NamedPlanetAssemblyIndex
    from ._992 import NamedPlanetSideBandAmplitudeFactor
    from ._993 import ReadonlyToothThicknessSpecification
    from ._994 import RelativeMeasurementViewModel
    from ._995 import RelativeValuesSpecification
    from ._996 import Scuffing
    from ._997 import ScuffingCoefficientOfFrictionMethods
    from ._998 import ScuffingTemperatureMethodsAGMA
    from ._999 import ScuffingTemperatureMethodsISO
    from ._1000 import ShaperEdgeTypes
    from ._1001 import SpurGearLoadSharingCodes
    from ._1002 import StandardRack
    from ._1003 import StandardRackFlank
    from ._1004 import SurfaceRoughness
    from ._1005 import ThicknessType
    from ._1006 import TiffAnalysisSettings
    from ._1007 import TipAlterationCoefficientMethod
    from ._1008 import TolerancedMetalMeasurements
    from ._1009 import TolerancedValueSpecification
    from ._1010 import ToothThicknessSpecification
    from ._1011 import ToothThicknessSpecificationBase
    from ._1012 import TypeOfMechanismHousing
    from ._1013 import Usage
