__title__ = 'consign'
__description__ = 'Python storage for humans.'
__url__ = 'https://requests.readthedocs.io'
__version__ = '0.1.4'
__author__ = 'Daniel Jadraque'
__author_email__ = 'jadraque@hey.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2021 Daniel Jadraque'