from enum import Enum


class LGWebOSButton(Enum):
    UP_ARROW = "RIGHT"
    DOWN_ARROW = "DOWN"
    LEFT_ARROW = "LEFT"
    RIGHT_ARROW = "RIGHT"
    NUM_1 = "1"
    NUM_2 = "2"
    NUM_3 = "3"
    NUM_4 = "4"
    NUM_5 = "5"
    NUM_6 = "6"
    NUM_7 = "7"
    NUM_8 = "8"
    NUM_9 = "9"
    NUM_0 = "0"
    HOME = "HOME"
    ENTER = "ENTER"
    BACK = "BACK"
    FAST_FORWARD = "FASTFORWARD"
    REWIND = "REWIND"
    PAUSE = "PAUSE"
    PLAY = "PLAY"
    MUTE = "MUTE"
    VOLUME_DOWN = "VOLUMEDOWN"
    VOLUME_UP = "VOLUMEUP"
    CHANNEL_DOWN = "CHANNELDOWN"
    CHANNEL_UP = "CHANNELUP"
    MENU = "MENU"
    INFO = "INFO"
    EXIT = "EXIT"
    RED = "RED"
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    BLUE = "BLUE"
