from enum import Enum


class TizenTVButton(Enum):
    UP_ARROW = "KEY_UP"
    DOWN_ARROW = "KEY_DOWN"
    LEFT_ARROW = "KEY_LEFT"
    RIGHT_ARROW = "KEY_RIGHT"
    NUM_1 = "KEY_1"
    NUM_2 = "KEY_2"
    NUM_3 = "KEY_3"
    NUM_4 = "KEY_4"
    NUM_5 = "KEY_5"
    NUM_6 = "KEY_6"
    NUM_7 = "KEY_7"
    NUM_8 = "KEY_8"
    NUM_9 = "KEY_9"
    NUM_0 = "KEY_0"
    HOME = "KEY_HOME"
    ENTER = "KEY_ENTER"
    RETURN = "KEY_RETURN"
    FAST_FORWARD = "KEY_FF"
    REWIND = "KEY_REWIND"
    PAUSE = "KEY_PAUSE"
    PLAY = "KEY_PLAY"
    INSTANT_REPLAY = "KEY_INSTANT_REPLAY"
    MUTE = "KEY_MUTE"
    VOLUME_DOWN = "KEY_VOLDOWN"
    VOLUME_UP = "KEY_VOLUP"
    CHANNEL_DOWN = "KEY_CHDOWN"
    CHANNEL_UP = "KEY_CHUP"
    GUIDE = "KEY_GUIDE"
    MENU = "KEY_MENU"
    INFO = "KEY_INFO"
