from . import subscription_request
from . import coop_agreement
from . import res_partner
from . import res_partner_bank
from . import contract
from . import service_technology
from . import service_supplier
from . import product_category_technology_supplier
from . import ir_model_data
from . import crm_lead
from . import crm_lead_line
from . import previous_provider
from . import discovery_channel
from . import isp_info
from . import stock_production_lot
from . import stock_move_line
from . import contract_info
from . import product_product
from . import account_invoice
from . import account_invoice_line
from . import account_journal
from . import account_tax
from . import account_move_line
from . import account_banking_mandate
from . import partner_otrs_view
from . import mail_activity
from . import res_company
from . import ir_server_action
