
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-19T04:26:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebd12c3b6573dd25ce55d954f322fed19c402d12",
 "version": "1.15.0.post.dev95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
