# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DockerSection(Model):
    """DockerSection.

    :param base_image:
    :type base_image: str
    :param platform:
    :type platform: ~designer.models.DockerImagePlatform
    :param base_dockerfile:
    :type base_dockerfile: str
    :param base_image_registry:
    :type base_image_registry: ~designer.models.ContainerRegistry
    """

    _attribute_map = {
        'base_image': {'key': 'baseImage', 'type': 'str'},
        'platform': {'key': 'platform', 'type': 'DockerImagePlatform'},
        'base_dockerfile': {'key': 'baseDockerfile', 'type': 'str'},
        'base_image_registry': {'key': 'baseImageRegistry', 'type': 'ContainerRegistry'},
    }

    def __init__(self, **kwargs):
        super(DockerSection, self).__init__(**kwargs)
        self.base_image = kwargs.get('base_image', None)
        self.platform = kwargs.get('platform', None)
        self.base_dockerfile = kwargs.get('base_dockerfile', None)
        self.base_image_registry = kwargs.get('base_image_registry', None)
