# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DebugInfoResponse(Model):
    """DebugInfoResponse.

    :param type:
    :type type: str
    :param message:
    :type message: str
    :param stack_trace:
    :type stack_trace: str
    :param inner_exception:
    :type inner_exception: ~_restclient.models.DebugInfoResponse
    :param data:
    :type data: dict[str, object]
    :param error_response:
    :type error_response: ~_restclient.models.ErrorResponse
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'stack_trace': {'key': 'stackTrace', 'type': 'str'},
        'inner_exception': {'key': 'innerException', 'type': 'DebugInfoResponse'},
        'data': {'key': 'data', 'type': '{object}'},
        'error_response': {'key': 'errorResponse', 'type': 'ErrorResponse'},
    }

    def __init__(self, *, type: str=None, message: str=None, stack_trace: str=None, inner_exception=None, data=None, error_response=None, **kwargs) -> None:
        super(DebugInfoResponse, self).__init__(**kwargs)
        self.type = type
        self.message = message
        self.stack_trace = stack_trace
        self.inner_exception = inner_exception
        self.data = data
        self.error_response = error_response
