# coding: utf-8

"""
    AristaFlowREST/ResModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_res_model_manager
from af_res_model_manager.models.plain_text_exception import PlainTextException  # noqa: E501
from af_res_model_manager.rest import ApiException


class TestPlainTextException(unittest.TestCase):
    """PlainTextException unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlainTextException(self):
        """Test PlainTextException"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_res_model_manager.models.plain_text_exception.PlainTextException()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
