HSM_STATE_ARMED_AWAY = 'armedAway'
HSM_STATE_ARMED_HOME = 'armedHome'
HSM_STATE_ARMED_NIGHT = 'armedNight'
HSM_STATE_DISARMED = 'disarmed'
HSM_STATE_ALL_DISARMED = 'allDisarmed'

HSM_ACTION_ARM_AWAY = 'armAway'
HSM_ACTION_ARM_HOME = 'armHome'
HSM_ACTION_ARM_NIGHT = 'armNight'
HSM_ACTION_DISARM = 'disarm'
HSM_ACTION_DISARM_ALL = 'disarmAll'
HSM_ACTION_CANCEL_ALERTS = 'cancelAlerts'

HSM_STATE_TO_ACTION = {
    HSM_STATE_ARMED_AWAY: HSM_ACTION_ARM_AWAY,
    HSM_STATE_ARMED_HOME: HSM_ACTION_ARM_HOME,
    HSM_STATE_ARMED_NIGHT: HSM_ACTION_ARM_NIGHT,
    HSM_STATE_DISARMED: HSM_ACTION_DISARM,
    HSM_STATE_ALL_DISARMED: HSM_ACTION_DISARM_ALL,
}
