# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsec/core/gui/forms/claim_user_provide_info_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClaimUserProvideInfoWidget(object):
    def setupUi(self, ClaimUserProvideInfoWidget):
        ClaimUserProvideInfoWidget.setObjectName("ClaimUserProvideInfoWidget")
        ClaimUserProvideInfoWidget.resize(400, 377)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClaimUserProvideInfoWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(ClaimUserProvideInfoWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.widget_info = QtWidgets.QWidget(ClaimUserProvideInfoWidget)
        self.widget_info.setObjectName("widget_info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_info)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_user_full_name = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_full_name.setFont(font)
        self.label_user_full_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_full_name.setObjectName("label_user_full_name")
        self.verticalLayout_7.addWidget(self.label_user_full_name)
        self.line_edit_user_full_name = ValidatedLineEdit(self.widget_info)
        self.line_edit_user_full_name.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_user_full_name.setFont(font)
        self.line_edit_user_full_name.setObjectName("line_edit_user_full_name")
        self.verticalLayout_7.addWidget(self.line_edit_user_full_name)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_device = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_device.setFont(font)
        self.label_device.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_device.setObjectName("label_device")
        self.verticalLayout_8.addWidget(self.label_device)
        self.line_edit_device = ValidatedLineEdit(self.widget_info)
        self.line_edit_device.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_device.setFont(font)
        self.line_edit_device.setText("")
        self.line_edit_device.setObjectName("line_edit_device")
        self.verticalLayout_8.addWidget(self.line_edit_device)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_user_email = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_email.setFont(font)
        self.label_user_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_email.setObjectName("label_user_email")
        self.verticalLayout_9.addWidget(self.label_user_email)
        self.line_edit_user_email = ValidatedLineEdit(self.widget_info)
        self.line_edit_user_email.setEnabled(True)
        self.line_edit_user_email.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_user_email.setFont(font)
        self.line_edit_user_email.setReadOnly(True)
        self.line_edit_user_email.setObjectName("line_edit_user_email")
        self.verticalLayout_9.addWidget(self.line_edit_user_email)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout.addWidget(self.widget_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.button_ok = QtWidgets.QPushButton(ClaimUserProvideInfoWidget)
        self.button_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_ok.setObjectName("button_ok")
        self.horizontalLayout_3.addWidget(self.button_ok)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_wait = QtWidgets.QLabel(ClaimUserProvideInfoWidget)
        self.label_wait.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wait.setObjectName("label_wait")
        self.verticalLayout.addWidget(self.label_wait)

        self.retranslateUi(ClaimUserProvideInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(ClaimUserProvideInfoWidget)

    def retranslateUi(self, ClaimUserProvideInfoWidget):
        _translate = QtCore.QCoreApplication.translate
        ClaimUserProvideInfoWidget.setWindowTitle(_translate("ClaimUserProvideInfoWidget", "Form"))
        self.label_4.setText(_translate("ClaimUserProvideInfoWidget", "TEXT_CLAIM_USER_PROVIDE_INFO_INSTRUCTIONS"))
        self.label_user_full_name.setText(_translate("ClaimUserProvideInfoWidget", "TEXT_LABEL_USER_FULL_NAME"))
        self.line_edit_user_full_name.setPlaceholderText(_translate("ClaimUserProvideInfoWidget", "TEXT_LABEL_USER_FULL_NAME_PLACEHOLDER"))
        self.label_device.setText(_translate("ClaimUserProvideInfoWidget", "TEXT_LABEL_DEVICE"))
        self.line_edit_device.setPlaceholderText(_translate("ClaimUserProvideInfoWidget", "TEXT_LABEL_DEVICE_PLACEHOLDER"))
        self.label_user_email.setText(_translate("ClaimUserProvideInfoWidget", "TEXT_LABEL_USER_EMAIL"))
        self.line_edit_user_email.setPlaceholderText(_translate("ClaimUserProvideInfoWidget", "TEXT_LABEL_USER_EMAIL_PLACEHOLDER"))
        self.button_ok.setText(_translate("ClaimUserProvideInfoWidget", "ACTION_OK"))
        self.label_wait.setText(_translate("ClaimUserProvideInfoWidget", "TEXT_CLAIM_USER_WAIT_FOR_USER_INFO"))
from parsec.core.gui.input_widgets import ValidatedLineEdit
