# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsec/core/gui/forms/create_org_user_info_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateOrgUserInfoWidget(object):
    def setupUi(self, CreateOrgUserInfoWidget):
        CreateOrgUserInfoWidget.setObjectName("CreateOrgUserInfoWidget")
        CreateOrgUserInfoWidget.resize(400, 385)
        CreateOrgUserInfoWidget.setStyleSheet("#CreateOrgUserInfoWidget, #scrollAreaWidgetContents {\n"
"    background-color: #F4F4F4;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateOrgUserInfoWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(CreateOrgUserInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.line_edit_user_full_name = QtWidgets.QLineEdit(CreateOrgUserInfoWidget)
        self.line_edit_user_full_name.setObjectName("line_edit_user_full_name")
        self.verticalLayout_10.addWidget(self.line_edit_user_full_name)
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(CreateOrgUserInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.line_edit_user_email = ValidatedLineEdit(CreateOrgUserInfoWidget)
        self.line_edit_user_email.setObjectName("line_edit_user_email")
        self.verticalLayout_3.addWidget(self.line_edit_user_email)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(CreateOrgUserInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.line_edit_org_name = ValidatedLineEdit(CreateOrgUserInfoWidget)
        self.line_edit_org_name.setObjectName("line_edit_org_name")
        self.verticalLayout_11.addWidget(self.line_edit_org_name)
        self.label_10 = QtWidgets.QLabel(CreateOrgUserInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radio_use_commercial = QtWidgets.QRadioButton(CreateOrgUserInfoWidget)
        self.radio_use_commercial.setObjectName("radio_use_commercial")
        self.verticalLayout_5.addWidget(self.radio_use_commercial)
        self.widget_contract = QtWidgets.QWidget(CreateOrgUserInfoWidget)
        self.widget_contract.setObjectName("widget_contract")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_contract)
        self.horizontalLayout_2.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_accept_contract = QtWidgets.QCheckBox(self.widget_contract)
        self.check_accept_contract.setMinimumSize(QtCore.QSize(25, 0))
        self.check_accept_contract.setMaximumSize(QtCore.QSize(25, 16777215))
        self.check_accept_contract.setText("")
        self.check_accept_contract.setObjectName("check_accept_contract")
        self.horizontalLayout_2.addWidget(self.check_accept_contract)
        self.label = QtWidgets.QLabel(self.widget_contract)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.widget_contract)
        self.radio_use_custom = QtWidgets.QRadioButton(CreateOrgUserInfoWidget)
        self.radio_use_custom.setObjectName("radio_use_custom")
        self.verticalLayout_5.addWidget(self.radio_use_custom)
        self.widget_custom_backend = QtWidgets.QWidget(CreateOrgUserInfoWidget)
        self.widget_custom_backend.setObjectName("widget_custom_backend")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_custom_backend)
        self.verticalLayout_2.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_edit_backend_addr = ValidatedLineEdit(self.widget_custom_backend)
        self.line_edit_backend_addr.setMinimumSize(QtCore.QSize(0, 0))
        self.line_edit_backend_addr.setObjectName("line_edit_backend_addr")
        self.verticalLayout_2.addWidget(self.line_edit_backend_addr)
        self.verticalLayout_5.addWidget(self.widget_custom_backend)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(CreateOrgUserInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateOrgUserInfoWidget)

    def retranslateUi(self, CreateOrgUserInfoWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateOrgUserInfoWidget.setWindowTitle(_translate("CreateOrgUserInfoWidget", "Form"))
        self.label_8.setText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_USER_FULL_NAME"))
        self.line_edit_user_full_name.setPlaceholderText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_USER_FULL_NAME_PLACEHOLDER"))
        self.label_13.setText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_USER_EMAIL"))
        self.line_edit_user_email.setPlaceholderText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_USER_EMAIL_PLACEHOLDER"))
        self.label_9.setText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_ORG_NAME"))
        self.label_10.setText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_ORG_NAME_RECOMMANDATIONS"))
        self.radio_use_commercial.setText(_translate("CreateOrgUserInfoWidget", "ACTION_CREATE_ON_COMMERCIAL_BACKEND"))
        self.label.setText(_translate("CreateOrgUserInfoWidget", "ACTION_ACCEPT_CONTRACT"))
        self.radio_use_custom.setText(_translate("CreateOrgUserInfoWidget", "ACTION_USE_CUSTOM_BACKEND"))
        self.line_edit_backend_addr.setPlaceholderText(_translate("CreateOrgUserInfoWidget", "TEXT_LABEL_BACKEND_ADDR_PLACEHOLDER"))
from parsec.core.gui.input_widgets import ValidatedLineEdit
