# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsec/core/gui/forms/greet_user_check_info_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GreetUserCheckInfoWidget(object):
    def setupUi(self, GreetUserCheckInfoWidget):
        GreetUserCheckInfoWidget.setObjectName("GreetUserCheckInfoWidget")
        GreetUserCheckInfoWidget.resize(596, 356)
        GreetUserCheckInfoWidget.setStyleSheet("#label_warning {\n"
"    color: #F1962B;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(GreetUserCheckInfoWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_waiting = QtWidgets.QLabel(GreetUserCheckInfoWidget)
        self.label_waiting.setWordWrap(True)
        self.label_waiting.setObjectName("label_waiting")
        self.verticalLayout.addWidget(self.label_waiting)
        self.widget_info = QtWidgets.QWidget(GreetUserCheckInfoWidget)
        self.widget_info.setObjectName("widget_info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_info)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_user_full_name = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_full_name.setFont(font)
        self.label_user_full_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_full_name.setObjectName("label_user_full_name")
        self.verticalLayout_7.addWidget(self.label_user_full_name)
        self.line_edit_user_full_name = ValidatedLineEdit(self.widget_info)
        self.line_edit_user_full_name.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_user_full_name.setFont(font)
        self.line_edit_user_full_name.setPlaceholderText("")
        self.line_edit_user_full_name.setObjectName("line_edit_user_full_name")
        self.verticalLayout_7.addWidget(self.line_edit_user_full_name)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_user_email = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_email.setFont(font)
        self.label_user_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_email.setObjectName("label_user_email")
        self.verticalLayout_9.addWidget(self.label_user_email)
        self.line_edit_user_email = ValidatedLineEdit(self.widget_info)
        self.line_edit_user_email.setEnabled(True)
        self.line_edit_user_email.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_user_email.setFont(font)
        self.line_edit_user_email.setReadOnly(True)
        self.line_edit_user_email.setPlaceholderText("")
        self.line_edit_user_email.setObjectName("line_edit_user_email")
        self.verticalLayout_9.addWidget(self.line_edit_user_email)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_device = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_device.setFont(font)
        self.label_device.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_device.setObjectName("label_device")
        self.verticalLayout_8.addWidget(self.label_device)
        self.line_edit_device = ValidatedLineEdit(self.widget_info)
        self.line_edit_device.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_device.setFont(font)
        self.line_edit_device.setPlaceholderText("")
        self.line_edit_device.setObjectName("line_edit_device")
        self.verticalLayout_8.addWidget(self.line_edit_device)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.combo_profile = QtWidgets.QComboBox(self.widget_info)
        self.combo_profile.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_profile.setFont(font)
        self.combo_profile.setObjectName("combo_profile")
        self.verticalLayout_3.addWidget(self.combo_profile)
        self.label_warning = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_warning.setFont(font)
        self.label_warning.setWordWrap(True)
        self.label_warning.setObjectName("label_warning")
        self.verticalLayout_3.addWidget(self.label_warning)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_create_user = QtWidgets.QPushButton(self.widget_info)
        self.button_create_user.setEnabled(False)
        self.button_create_user.setObjectName("button_create_user")
        self.horizontalLayout.addWidget(self.button_create_user)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget_info)

        self.retranslateUi(GreetUserCheckInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(GreetUserCheckInfoWidget)

    def retranslateUi(self, GreetUserCheckInfoWidget):
        _translate = QtCore.QCoreApplication.translate
        GreetUserCheckInfoWidget.setWindowTitle(_translate("GreetUserCheckInfoWidget", "Form"))
        self.label_waiting.setText(_translate("GreetUserCheckInfoWidget", "TEXT_GREET_USER_WAITING_FOR_INFO"))
        self.label_user_full_name.setText(_translate("GreetUserCheckInfoWidget", "TEXT_LABEL_USER_FULL_NAME"))
        self.label_user_email.setText(_translate("GreetUserCheckInfoWidget", "TEXT_LABEL_USER_EMAIL"))
        self.label_device.setText(_translate("GreetUserCheckInfoWidget", "TEXT_LABEL_DEVICE"))
        self.label.setText(_translate("GreetUserCheckInfoWidget", "TEXT_LABEL_USER_ROLE"))
        self.combo_profile.setToolTip(_translate("GreetUserCheckInfoWidget", "TEXT_USER_ROLES_TOOLTIP"))
        self.label_warning.setText(_translate("GreetUserCheckInfoWidget", "TEXT_LABEL_USER_ROLE_RECOMMANDATIONS"))
        self.button_create_user.setText(_translate("GreetUserCheckInfoWidget", "ACTION_CREATE_USER"))
from parsec.core.gui.input_widgets import ValidatedLineEdit
