# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsec/core/gui/forms/timestamped_workspace_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimestampedWorkspaceWidget(object):
    def setupUi(self, TimestampedWorkspaceWidget):
        TimestampedWorkspaceWidget.setObjectName("TimestampedWorkspaceWidget")
        TimestampedWorkspaceWidget.resize(549, 490)
        TimestampedWorkspaceWidget.setStyleSheet("#button_show {\n"
"    text-transform: uppercase;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(TimestampedWorkspaceWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(TimestampedWorkspaceWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_info = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_info.setFont(font)
        self.label_info.setText("")
        self.label_info.setWordWrap(True)
        self.label_info.setObjectName("label_info")
        self.verticalLayout_2.addWidget(self.label_info)
        self.widget_reencrypt = QtWidgets.QWidget(self.widget)
        self.widget_reencrypt.setObjectName("widget_reencrypt")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_reencrypt)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_reencrypt)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.calendar_widget = CalendarWidget(self.widget_reencrypt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar_widget.sizePolicy().hasHeightForWidth())
        self.calendar_widget.setSizePolicy(sizePolicy)
        self.calendar_widget.setStyleSheet("")
        self.calendar_widget.setObjectName("calendar_widget")
        self.horizontalLayout_3.addWidget(self.calendar_widget)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_time = QtWidgets.QLabel(self.widget_reencrypt)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setWordWrap(True)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_4.addWidget(self.label_time)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.time_edit = QtWidgets.QTimeEdit(self.widget_reencrypt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_edit.sizePolicy().hasHeightForWidth())
        self.time_edit.setSizePolicy(sizePolicy)
        self.time_edit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.time_edit.setFont(font)
        self.time_edit.setObjectName("time_edit")
        self.horizontalLayout.addWidget(self.time_edit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.button_show = QtWidgets.QPushButton(self.widget_reencrypt)
        self.button_show.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        self.button_show.setFont(font)
        self.button_show.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_show.setIconSize(QtCore.QSize(20, 20))
        self.button_show.setObjectName("button_show")
        self.horizontalLayout_2.addWidget(self.button_show)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.widget_reencrypt)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(TimestampedWorkspaceWidget)
        QtCore.QMetaObject.connectSlotsByName(TimestampedWorkspaceWidget)

    def retranslateUi(self, TimestampedWorkspaceWidget):
        _translate = QtCore.QCoreApplication.translate
        TimestampedWorkspaceWidget.setWindowTitle(_translate("TimestampedWorkspaceWidget", "Form"))
        self.label.setText(_translate("TimestampedWorkspaceWidget", "TEXT_WORKSPACE_TIMESTAMPED_SELECT_DATE"))
        self.label_time.setText(_translate("TimestampedWorkspaceWidget", "TEXT_WORKSPACE_TIMESTAMPED_SELECT_TIME"))
        self.button_show.setText(_translate("TimestampedWorkspaceWidget", "ACTION_WORKSPACE_TIMESTAMPED_MOUNT"))
from parsec.core.gui.calendar_widget import CalendarWidget
