# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsec/core/gui/forms/workspace_button.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkspaceButton(object):
    def setupUi(self, WorkspaceButton):
        WorkspaceButton.setObjectName("WorkspaceButton")
        WorkspaceButton.resize(300, 250)
        WorkspaceButton.setMinimumSize(QtCore.QSize(300, 250))
        WorkspaceButton.setMaximumSize(QtCore.QSize(300, 250))
        font = QtGui.QFont()
        font.setPointSize(12)
        WorkspaceButton.setFont(font)
        WorkspaceButton.setAccessibleDescription("")
        WorkspaceButton.setStyleSheet("QWidget#WorkspaceButton {\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QWidget#widget {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 0;\n"
"    background-color: none;\n"
"}\n"
"\n"
"QWidget#widget_actions {\n"
"    background-color: #FFFFFF;\n"
"    border-bottom-left-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QWidget#widget_title {\n"
"    background-color: #FFFFFF;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"}\n"
"\n"
"#file1_name, #file2_name, #file3_name, #file4_name {\n"
"    color: #999999;\n"
"}\n"
"\n"
"#label_role {\n"
"    color: #999999;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(WorkspaceButton)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(WorkspaceButton)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_title = QtWidgets.QWidget(self.widget)
        self.widget_title.setMinimumSize(QtCore.QSize(0, 70))
        self.widget_title.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_title.setStyleSheet("")
        self.widget_title.setObjectName("widget_title")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_title)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_title = QtWidgets.QLabel(self.widget_title)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setText("")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_4.addWidget(self.label_title)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.badge_widget = QtWidgets.QWidget(self.widget_title)
        self.badge_widget.setObjectName("badge_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.badge_widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_role = QtWidgets.QLabel(self.badge_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_role.setFont(font)
        self.label_role.setObjectName("label_role")
        self.horizontalLayout_5.addWidget(self.label_role)
        self.horizontalLayout_4.addWidget(self.badge_widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.label_shared = IconLabel(self.widget_title)
        self.label_shared.setMinimumSize(QtCore.QSize(24, 24))
        self.label_shared.setMaximumSize(QtCore.QSize(24, 24))
        self.label_shared.setText("")
        self.label_shared.setPixmap(QtGui.QPixmap(":/icons/images/material/folder_shared.svg"))
        self.label_shared.setScaledContents(True)
        self.label_shared.setProperty("color", QtGui.QColor(153, 153, 153))
        self.label_shared.setObjectName("label_shared")
        self.horizontalLayout.addWidget(self.label_shared)
        self.label_owner = IconLabel(self.widget_title)
        self.label_owner.setMinimumSize(QtCore.QSize(24, 24))
        self.label_owner.setMaximumSize(QtCore.QSize(24, 24))
        self.label_owner.setText("")
        self.label_owner.setPixmap(QtGui.QPixmap(":/icons/images/material/grade.svg"))
        self.label_owner.setScaledContents(True)
        self.label_owner.setProperty("color", QtGui.QColor(153, 153, 153))
        self.label_owner.setObjectName("label_owner")
        self.horizontalLayout.addWidget(self.label_owner)
        self.verticalLayout_2.addWidget(self.widget_title)
        self.widget_files = QtWidgets.QWidget(self.widget)
        self.widget_files.setStyleSheet("")
        self.widget_files.setObjectName("widget_files")
        self.formLayout = QtWidgets.QFormLayout(self.widget_files)
        self.formLayout.setContentsMargins(15, 15, 15, 15)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.file1_icon = QtWidgets.QLabel(self.widget_files)
        self.file1_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.file1_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.file1_icon.setText("")
        self.file1_icon.setScaledContents(True)
        self.file1_icon.setObjectName("file1_icon")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.file1_icon)
        self.file1_name = QtWidgets.QLabel(self.widget_files)
        self.file1_name.setText("")
        self.file1_name.setObjectName("file1_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.file1_name)
        self.file2_icon = QtWidgets.QLabel(self.widget_files)
        self.file2_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.file2_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.file2_icon.setText("")
        self.file2_icon.setScaledContents(True)
        self.file2_icon.setObjectName("file2_icon")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.file2_icon)
        self.file2_name = QtWidgets.QLabel(self.widget_files)
        self.file2_name.setText("")
        self.file2_name.setObjectName("file2_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.file2_name)
        self.file3_icon = QtWidgets.QLabel(self.widget_files)
        self.file3_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.file3_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.file3_icon.setText("")
        self.file3_icon.setScaledContents(True)
        self.file3_icon.setObjectName("file3_icon")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.file3_icon)
        self.file3_name = QtWidgets.QLabel(self.widget_files)
        self.file3_name.setText("")
        self.file3_name.setObjectName("file3_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.file3_name)
        self.file4_icon = QtWidgets.QLabel(self.widget_files)
        self.file4_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.file4_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.file4_icon.setText("")
        self.file4_icon.setScaledContents(True)
        self.file4_icon.setObjectName("file4_icon")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.file4_icon)
        self.file4_name = QtWidgets.QLabel(self.widget_files)
        self.file4_name.setText("")
        self.file4_name.setObjectName("file4_name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.file4_name)
        self.verticalLayout_2.addWidget(self.widget_files)
        self.widget_empty = QtWidgets.QWidget(self.widget)
        self.widget_empty.setObjectName("widget_empty")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_empty)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addWidget(self.widget_empty)
        self.widget_reencryption = QtWidgets.QWidget(self.widget)
        self.widget_reencryption.setObjectName("widget_reencryption")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_reencryption)
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progress_reencryption = QtWidgets.QProgressBar(self.widget_reencryption)
        self.progress_reencryption.setProperty("value", 0)
        self.progress_reencryption.setObjectName("progress_reencryption")
        self.horizontalLayout_3.addWidget(self.progress_reencryption)
        self.verticalLayout_2.addWidget(self.widget_reencryption)
        self.widget_actions = QtWidgets.QWidget(self.widget)
        self.widget_actions.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_actions.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_actions.setStyleSheet("")
        self.widget_actions.setObjectName("widget_actions")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_actions)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.button_open = Button(self.widget_actions)
        self.button_open.setMinimumSize(QtCore.QSize(32, 32))
        self.button_open.setMaximumSize(QtCore.QSize(32, 32))
        self.button_open.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/material/open_in_browser.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_open.setIcon(icon)
        self.button_open.setIconSize(QtCore.QSize(24, 24))
        self.button_open.setFlat(True)
        self.button_open.setProperty("color", QtGui.QColor(153, 153, 153))
        self.button_open.setObjectName("button_open")
        self.horizontalLayout_2.addWidget(self.button_open)
        self.button_rename = Button(self.widget_actions)
        self.button_rename.setMinimumSize(QtCore.QSize(32, 32))
        self.button_rename.setMaximumSize(QtCore.QSize(32, 32))
        self.button_rename.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_rename.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/material/create.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_rename.setIcon(icon1)
        self.button_rename.setIconSize(QtCore.QSize(24, 24))
        self.button_rename.setFlat(True)
        self.button_rename.setProperty("color", QtGui.QColor(153, 153, 153))
        self.button_rename.setObjectName("button_rename")
        self.horizontalLayout_2.addWidget(self.button_rename)
        self.button_share = Button(self.widget_actions)
        self.button_share.setMinimumSize(QtCore.QSize(32, 32))
        self.button_share.setMaximumSize(QtCore.QSize(32, 32))
        self.button_share.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_share.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/material/share.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_share.setIcon(icon2)
        self.button_share.setIconSize(QtCore.QSize(24, 24))
        self.button_share.setFlat(True)
        self.button_share.setProperty("color", QtGui.QColor(153, 153, 153))
        self.button_share.setObjectName("button_share")
        self.horizontalLayout_2.addWidget(self.button_share)
        self.button_remount_ts = Button(self.widget_actions)
        self.button_remount_ts.setMinimumSize(QtCore.QSize(32, 32))
        self.button_remount_ts.setMaximumSize(QtCore.QSize(32, 32))
        self.button_remount_ts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_remount_ts.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/material/date_range.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_remount_ts.setIcon(icon3)
        self.button_remount_ts.setIconSize(QtCore.QSize(24, 24))
        self.button_remount_ts.setFlat(True)
        self.button_remount_ts.setProperty("color", QtGui.QColor(153, 153, 153))
        self.button_remount_ts.setObjectName("button_remount_ts")
        self.horizontalLayout_2.addWidget(self.button_remount_ts)
        self.button_reencrypt = Button(self.widget_actions)
        self.button_reencrypt.setMinimumSize(QtCore.QSize(32, 32))
        self.button_reencrypt.setMaximumSize(QtCore.QSize(32, 32))
        self.button_reencrypt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_reencrypt.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/material/lock_outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_reencrypt.setIcon(icon4)
        self.button_reencrypt.setIconSize(QtCore.QSize(32, 32))
        self.button_reencrypt.setFlat(True)
        self.button_reencrypt.setProperty("color", QtGui.QColor(244, 67, 54))
        self.button_reencrypt.setObjectName("button_reencrypt")
        self.horizontalLayout_2.addWidget(self.button_reencrypt)
        self.button_delete = Button(self.widget_actions)
        self.button_delete.setMinimumSize(QtCore.QSize(32, 32))
        self.button_delete.setMaximumSize(QtCore.QSize(32, 32))
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/material/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete.setIcon(icon5)
        self.button_delete.setIconSize(QtCore.QSize(24, 24))
        self.button_delete.setFlat(True)
        self.button_delete.setProperty("color", QtGui.QColor(153, 153, 153))
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout_2.addWidget(self.button_delete)
        self.verticalLayout_2.addWidget(self.widget_actions)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(WorkspaceButton)
        QtCore.QMetaObject.connectSlotsByName(WorkspaceButton)

    def retranslateUi(self, WorkspaceButton):
        _translate = QtCore.QCoreApplication.translate
        WorkspaceButton.setWindowTitle(_translate("WorkspaceButton", "Form"))
        self.label_shared.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_IS_SHARED_TOOLTIP"))
        self.label_owner.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_IS_OWNER_TOOLTIP"))
        self.progress_reencryption.setFormat(_translate("WorkspaceButton", "TEXT_WORKSPACE_REENCRYPTION"))
        self.button_open.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_OPEN_WORKSPACE_TOOLTIP"))
        self.button_rename.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_RENAME_TOOLTIP"))
        self.button_share.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_OPEN_SHARING_TOOLTIP"))
        self.button_remount_ts.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_REMOUNT_TIMESTAMPED_TOOLTIP"))
        self.button_reencrypt.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_REENCRYPT_WORKSPACE_TOOLTIP"))
        self.button_delete.setToolTip(_translate("WorkspaceButton", "TEXT_WORKSPACE_DELETE_WORKSPACE_TOOLTIP"))
from parsec.core.gui.custom_widgets import Button, IconLabel
from parsec.core.gui import resources_rc
