# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.media_file_bundle_mini import MediaFileBundleMini  # noqa: E501
from elements_sdk.rest import ApiException

class TestMediaFileBundleMini(unittest.TestCase):
    """MediaFileBundleMini unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MediaFileBundleMini
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.media_file_bundle_mini.MediaFileBundleMini()  # noqa: E501
        if include_optional :
            return MediaFileBundleMini(
                id = 56, 
                asset = 56, 
                name = '0', 
                location = 56, 
                mainfile = elements_sdk.models.mainfile.Mainfile(
                    id = 56, 
                    name = '0', 
                    bundle = 56, 
                    full_path = '0', 
                    custom_fields = elements_sdk.models.custom_fields.Custom fields(), 
                    mtime = 56, 
                    parent = '0', 
                    path = '0', 
                    present = True, 
                    size = 56, 
                    volume = elements_sdk.models.volume.Volume(
                        id = 56, 
                        name = '0', 
                        path = '0', 
                        display_name = '0', 
                        visual_tag = '0', 
                        type = 'generic', ), )
            )
        else :
            return MediaFileBundleMini(
                asset = 56,
                name = '0',
                location = 56,
        )

    def testMediaFileBundleMini(self):
        """Test MediaFileBundleMini"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
